jobs:
  include:
#    - stage: python-unitests
#      language: python
#
#      python:
#        - 3.6
#
#      install:
#        - cd webapp
#        - pip install -r requirements_dev.txt
#
#      script:
#        - cd lang_game
#        - python manage.py migrate
#        - python manage.py loaddata sample_data
#        - python manage.py test

    - stage: deploy
      script:
        - echo "PROD SERVER IP ADDRESS:$DEPLOYMENT_PROD_SERVER_IP"
        - ssh-keyscan -F $DEPLOYMENT_PROD_SERVER_IP 2>&1 | tee -a $HOME/.ssh/known_hosts

        - ssh root@$DEPLOYMENT_PROD_SERVER_IP mkdir langgame/
        - scp ./* root@$DEPLOYMENT_PROD_SERVER_IP:langgame/
        - ssh root@$DEPLOYMENT_PROD_SERVER_IP:langgame/ "docker-compose up -d"
        - ssh root@$DEPLOYMENT_PROD_SERVER_IP:langgame/ "docker-compose run web /usr/local/bin/python manage.py migrate"



