jobs:
  include:
    - stage: python-unitests
      language: python
      python:
        - 3.6
      env:
        - DJANGO_SETTINGS_MODULE=lang_game.settings.local
      install:
        - pip install -r webapp/requirements_dev.txt

      script:
        - python webapp/manage.py migrate
        - python webapp/manage.py loaddata sample_data
        - python webapp/manage.py test

    - stage: prod-deploy
      env:
        - DJANGO_SETTINGS_MODULE=lang_game.settings.prod
      before_script:
        - mkdir -p ~/.ssh
        - echo -e $PROD_SSH_PRIVATE_KEY | tr -d '\r' > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - eval "$(ssh-agent -s)"
        - ssh-add ~/.ssh/id_rsa
        - ssh-keyscan $DEPLOYMENT_PROD_SERVER_IP 2>&1 | tee -a $HOME/.ssh/known_hosts
      script:
        - ENV_VARIABLES="export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE;export PROD_DJANGO_SECRET=$PROD_DJANGO_SECRET"
        - ssh root@$DEPLOYMENT_PROD_SERVER_IP mkdir -p langgame/
        - scp -r . root@$DEPLOYMENT_PROD_SERVER_IP:langgame/
        - ssh root@$DEPLOYMENT_PROD_SERVER_IP "$ENV_VARIABLES;docker-compose -f langgame/docker-compose.yml up -d"
        - ssh root@$DEPLOYMENT_PROD_SERVER_IP "$ENV_VARIABLES;docker-compose -f langgame/docker-compose.yml run web /usr/local/bin/python manage.py migrate"
