jobs:
  include:
    - stage: python-unitests
      language: python
      python:
        - 3.6

      install:
        - pip install -r webapp/requirements_dev.txt

      script:
        - python webapp/manage.py migrate
        - python webapp/manage.py loaddata sample_data
        - python webapp/manage.py test

    - stage: deploy
      before_script:
        - mkdir -p ~/.ssh
        - echo -e $PROD_SSH_PRIVATE_KEY | tr -d '\r' > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - eval "$(ssh-agent -s)"
        - ssh-add ~/.ssh/id_rsa
        - ssh-keyscan $DEPLOYMENT_PROD_SERVER_IP 2>&1 | tee -a $HOME/.ssh/known_hosts
      script:
        - echo "PROD SERVER IP ADDRESS:$DEPLOYMENT_PROD_SERVER_IP"

        - ssh root@$DEPLOYMENT_PROD_SERVER_IP mkdir -p langgame/
        - scp -r . root@$DEPLOYMENT_PROD_SERVER_IP:langgame/
        - ssh root@$DEPLOYMENT_PROD_SERVER_IP "docker-compose -f langgame/docker-compose.yml up -d"
        - ssh root@$DEPLOYMENT_PROD_SERVER_IP "docker-compose -f langgame/docker-compose.yml run web /usr/local/bin/python manage.py migrate"
