
jobs:
  include:
#    - stage: python-unitests
#      language: python
#
#      python:
#        - 3.6
#
#      install:
#        - cd webapp
#        - pip install -r requirements_dev.txt
#
#      script:
#        - cd lang_game
#        - python manage.py migrate
#        - python manage.py loaddata sample_data
#        - python manage.py test

    - stage: deploy
      script:
        - echo "PROD SERVER IP ADDRESS:$DEPLOYMENT_PROD_SERVER_IP"
        - ssh root@167.99.132.66 mkdir langgame/
        - scp ./* root@167.99.132.66:langgame/
        - ssh root@167.99.132.66:langgame/ "docker-compose up -d"
        - ssh root@167.99.132.66:langgame/ "docker-compose run web /usr/local/bin/python manage.py migrate"



