language: python

python: 
  - 3.6

install:
  - cd webapp/lang_game
  - pip install -r requirements.txt

script:
  - python manage.py migrate
  - python manage.py loaddata sample_data
  - python manage.py test