version: '3'
services:
  web:
    image: "michalnetik/langgame_backend:${VERSION_TAG}"
    environment:
      - DJANGO_SETTINGS_MODULE
      - DJANGO_SECRET
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - static:/static
    command: /usr/local/bin/gunicorn lang_game.wsgi:application -w 2 -b :8000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  frontend:
    image: "michalnetik/langgame_frontend:${VERSION_TAG}"
    expose:
      - "8001"

  nginx:
    image: "michalnetik/langgame_nginx:${VERSION_TAG}"
    ports:
      - "80:80"
    links:
      - web:web
      - frontend:frontend
    volumes:
      - static:/static
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  pgdata:
  static:
