version: '3'
services:
  web:
    image: "michalnetik/langgame_backend:${VERSION_TAG}"
    build: ./webapp/

  frontend:
    image: "michalnetik/langgame_frontend:${VERSION_TAG}"
    build: ./angular/

  nginx:
    image: "michalnetik/langgame_nginx:${VERSION_TAG}"
    build: ./nginx/

  postgres:
    image: postgres:latest

  e2e:
    image: "michalnetik/langgame_e2e:${VERSION_TAG}"
    build: ./angular/e2e
