version: '3'
services:
  web:
    image: "michalnetik/langggame_backend:${VERSION_TAG}"
    environment:
      - DJANGO_SETTINGS_MODULE
      - DJANGO_SECRET
    restart: always
    build: ./webapp/
    expose:
      - "8000"
    links:
      - postgres:postgres
    command: /usr/local/bin/gunicorn lang_game.wsgi:application -w 2 -b :8000

  frontend:
    image: "michalnetik/langgame_frontend:${VERSION_TAG}"
    restart: always
    build: ./angular/
    expose:
      - "8001"

  nginx:
    image: "michalnetik/langgame_nginx:${VERSION_TAG}"
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web:web
      - frontend:frontend

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  e2e:
    image: "michalnetik/langgame_e2e:${VERSION_TAG}"
    restart: always
    build: ./angular/e2e

volumes:
  pgdata:
